Suggested edits to implementations.md
w3c/wcag-act-rules pull request #99
Opened 2022-05-05 09:23 UTC by daniel-montalvo

* ACT Rules -> Test Rules for consistency with current WAI website wording.
* Edits to the summary box, adding information purpose and no W3C endorsement.
* "Add implementation" section at the very top
* Further edits to the "Understanding consistency" section.
* Use of "evaluation tools and test methodologies" throughout.

2022-05-09 10:17 UTC, WilcoFiers requested changes

2022-05-09 10:17 UTC, WilcoFiers commented on content/implementations.md
> +## Add a Tool or Methodology
Most people visiting this page are not going to need this info. I think it is better to keep it at the bottom.

2022-05-09 10:17 UTC, WilcoFiers commented on content/implementations.md
> +title: "Implementations"
I don't think the audience of this page is going to know what an implementation is.

2022-05-09 10:17 UTC, WilcoFiers commented on content/implementations.md
> +ACT Rules implementations provide obtained test outcomes based on the Test Rules expected results. Scores are based on public test data submitted by evaluation tool vendors and test methodology devel
1. I don't think we should use "evaluation tool". That's not how people talk about this type of software. I know WAI uses this term on its site in a few places. But I think ensuring people understand this content is more important than historic consistency.

2. It seems to me that this new summary is getting into too much detail. I would prefer we keep it very high level here. The current version does a better job of that I think. I do want to explicitly say that ACT rules lets us compare implementations. That's the whole point of this  #project.

3. Fair point on the non-endorsement, but does that need to be in the summary? Can we have that under its own heading instead?

4. I don't think "Test rules" as a generic term is right. "WCAG 2 Test Rules" works for rules that map to WCAG 2, but not "Test Rules" by itself is too generic I think.

2022-05-09 10:17 UTC, WilcoFiers commented on content/implementations.md
> +The ACT Rules Task Force is working on a user interface for submitting implementations (to be added soon). For current information on how to add your accessibility evaluation tool or test methodology
I wasn't planning to build any sort of UI around submitting an implementation. The current process seems to work reasonably well.

2022-05-09 10:17 UTC, WilcoFiers commented on content/implementations.md
> +Test methodologies provide step by step instructions on how to test accessibility requirements.
I used "standards" here to tie it into the "standards" column in the tables. They're both correct, but this seemed a little more appropriate.

2022-05-09 10:17 UTC, WilcoFiers commented on content/implementations.md
> +* An ACT implementation is **fully consistent** when all the following are true:
I'm not convinced about putting these as nested lists. It sort of suggests that fully consistent and partially consistent are more or less equivalent to each other. I don't think that's the case. Implementations should be fully consistent. You can get partial credit for not getting things wrong, but the emphasis should be on getting things right. A partial implementation didn't get it all right.

2022-05-10 15:49 UTC, closed without merging

2022-05-10 15:49 UTC, daniel-montalvo commented
Comments are now included in #95